"""Initial migration

Revision ID: 921808035b12
Revises:
Create Date: 2025-11-02 15:30:04.967151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "921808035b12"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipient", sa.String(255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=False)
    op.create_index(op.f("ix_message_read"), "message", ["read"], unique=False)
    op.create_index(
        op.f("ix_message_recipient"), "message", ["recipient"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_recipient"), table_name="message")
    op.drop_index(op.f("ix_message_read"), table_name="message")
    op.drop_index(op.f("ix_message_id"), table_name="message")
    op.drop_table("message")
    # ### end Alembic commands ###
